In [1]:
import pandas as pd
import numpy as np
from sklearn import pipeline,preprocessing,metrics,model_selection,ensemble
from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import OneHotEncoder

In [2]:
data=pd.read_excel(r'G:\DBA\MOD_2_core analytics\django\djangoTut\mpgWebApp\models\mileage_new.xls')

In [3]:
data.head()

    mpg  cyl   disp   hp    wt   acc  modyr  origin                       name
0  18.0    8  307.0  130  3504  12.0     70       1  chevrolet chevelle malibu
1  15.0    8  350.0  165  3693  11.5     70       1          buick skylark 320
2  18.0    8  318.0  150  3436  11.0     70       1         plymouth satellite
3  16.0    8  304.0  150  3433  12.0     70       1              amc rebel sst
4  17.0    8  302.0  140  3449  10.5     70       1                ford torino

In [57]:
data.shape

(392, 9)

In [50]:
data.isnull().sum()

mpg       0
cyl       0
disp      0
hp        0
wt        0
acc       0
modyr     0
origin    0
name      0
dtype: int64

In [51]:
mapper = DataFrameMapper([
                        (['cyl','disp','hp','wt','acc','modyr'],preprocessing.StandardScaler()),
])

In [52]:
pipeline_obj=pipeline.Pipeline([
    ("mapper",mapper),
    ("model",ensemble.RandomForestRegressor())
])

In [53]:
data.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'modyr', 'origin', 'name'], dtype='object')

In [54]:
X=['cyl', 'disp', 'hp', 'wt', 'acc', 'modyr']
Y=['mpg']

In [55]:
pipeline_obj.fit(data[X],data[Y])

c:\users\bhargav\lib\site-packages\sklearn\pipeline.py:346: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)

Pipeline(steps=[('mapper',
                 DataFrameMapper(drop_cols=[],
                                 features=[(['cyl', 'disp', 'hp', 'wt', 'acc',
                                             'modyr'],
                                            StandardScaler())])),
                ('model', RandomForestRegressor())])

In [56]:
pipeline_obj.predict(data[X])

array([17.439, 14.821, 16.92 , 16.26 , 17.072, 14.58 , 14.04 , 14.2  ,
       13.46 , 14.68 , 15.02 , 14.36 , 14.92 , 14.47 , 24.085, 21.49 ,
       18.88 , 21.005, 26.99 , 26.821, 24.226, 24.225, 24.47 , 25.22 ,
       20.8  , 10.8  , 11.055, 11.36 ,  9.84 , 27.06 , 26.411, 25.385,
       19.289, 16.776, 17.58 , 18.74 , 18.23 , 13.82 , 13.68 , 14.115,
       14.21 , 12.22 , 13.09 , 12.56 , 18.274, 22.185, 18.63 , 18.33 ,
       23.534, 26.94 , 30.04 , 29.215, 31.49 , 33.305, 27.955, 27.505,
       24.532, 25.59 , 23.665, 20.677, 22.229, 13.36 , 13.68 , 14.58 ,
       14.11 , 15.771, 11.74 , 12.88 , 12.41 , 12.93 , 20.814, 14.84 ,
       13.655, 13.505, 14.12 , 18.945, 22.608, 20.985, 26.355, 22.475,
       26.38 , 23.075, 27.345, 26.52 , 13.165, 14.461, 13.51 , 14.08 ,
       14.7  , 12.09 , 13.17 , 13.285, 14.05 , 12.57 , 12.22 , 13.39 ,
       18.315, 16.355, 18.232, 18.143, 21.964, 26.791, 11.6  , 12.25 ,
       12.85 , 12.405, 18.36 , 22.01 , 21.475, 23.06 , 21.395, 20.363,
       21.211, 25.97 , 14.51 , 15.1  , 29.29 , 24.955, 21.406, 19.799,
       15.052, 23.161, 19.704, 12.335, 20.328, 19.2  , 16.091, 30.8  ,
       25.355, 30.985, 24.683, 16.17 , 16.005, 17.733, 15.416, 13.27 ,
       13.985, 13.682, 14.162, 27.589, 27.52 , 26.374, 31.565, 31.655,
       27.2  , 25.14 , 25.894, 23.937, 25.483, 30.27 , 19.265, 17.844,
       15.739, 15.963, 15.095, 14.73 , 15.155, 14.28 , 17.063, 16.145,
       15.59 , 17.741, 20.125, 19.723, 15.197, 27.735, 23.513, 19.8  ,
       23.011, 23.939, 25.579, 23.83 , 18.883, 29.09 , 19.034, 23.372,
       22.552, 21.651, 23.74 , 32.475, 26.716, 25.184, 24.621, 25.985,
       27.37 , 16.47 , 15.455, 16.324, 14.885, 21.498, 20.92 , 22.868,
       21.17 , 29.822, 25.545, 29.26 , 32.76 , 19.692, 18.376, 18.511,
       18.243, 29.491, 31.605, 27.63 , 25.605, 20.127, 13.325, 20.083,
       19.777, 17.224, 15.645, 13.795, 13.721, 13.255, 31.509, 29.664,
       34.422, 25.347, 32.83 , 16.783, 17.207, 15.684, 15.347, 18.047,
       20.268, 19.212, 18.31 , 15.715, 15.54 , 15.728, 15.827, 29.845,
       24.505, 26.639, 24.875, 31.113, 32.455, 30.524, 29.805, 21.83 ,
       22.241, 22.091, 40.864, 35.405, 34.493, 36.879, 35.543, 19.774,
       18.822, 19.41 , 19.021, 20.24 , 20.714, 25.06 , 20.217, 19.766,
       20.605, 20.692, 18.728, 18.801, 18.922, 17.93 , 18.527, 17.089,
       30.669, 25.813, 26.769, 29.713, 22.99 , 22.98 , 23.342, 24.086,
       21.305, 17.641, 21.712, 16.901, 31.718, 30.461, 21.234, 21.544,
       24.327, 20.296, 20.598, 17.268, 17.873, 17.441, 17.792, 16.473,
       16.152, 19.337, 17.681, 33.499, 33.825, 35.019, 28.428, 25.274,
       21.11 , 27.85 , 22.721, 35.078, 34.343, 33.94 , 36.394, 28.068,
       27.707, 25.415, 32.016, 39.298, 36.591, 33.138, 36.605, 27.891,
       26.249, 25.523, 20.097, 34.689, 29.357, 31.169, 34.957, 32.672,
       43.216, 26.915, 41.027, 43.524, 40.832, 33.598, 30.554, 41.291,
       34.635, 31.819, 27.531, 28.632, 33.461, 32.558, 28.516, 27.104,
       26.251, 24.27 , 31.423, 37.688, 37.707, 35.722, 33.314, 36.708,
       36.518, 34.162, 34.813, 34.688, 32.776, 33.762, 34.166, 32.601,
       30.96 , 30.866, 27.869, 28.67 , 25.289, 25.29 , 21.717, 24.344,
       21.3  , 20.017, 28.51 , 27.919, 33.036, 30.454, 29.085, 27.061,
       24.705, 35.618, 36.07 , 33.005, 37.366, 35.105, 35.821, 35.42 ,
       33.801, 35.872, 33.301, 36.294, 25.658, 30.737, 27.243, 24.066,
       29.933, 34.114, 26.508, 26.806, 41.953, 32.689, 28.782, 30.12 ])

In [58]:
import joblib

In [62]:
joblib.dump(pipeline_obj,'RFModelforMPG5.pkl')

['RFModelforMPG5.pkl']

In [65]:
modelReload=joblib.load('RFModelforMPG5.pkl')

In [66]:
modelReload.predict(data[X])

array([17.439, 14.821, 16.92 , 16.26 , 17.072, 14.58 , 14.04 , 14.2  ,
       13.46 , 14.68 , 15.02 , 14.36 , 14.92 , 14.47 , 24.085, 21.49 ,
       18.88 , 21.005, 26.99 , 26.821, 24.226, 24.225, 24.47 , 25.22 ,
       20.8  , 10.8  , 11.055, 11.36 ,  9.84 , 27.06 , 26.411, 25.385,
       19.289, 16.776, 17.58 , 18.74 , 18.23 , 13.82 , 13.68 , 14.115,
       14.21 , 12.22 , 13.09 , 12.56 , 18.274, 22.185, 18.63 , 18.33 ,
       23.534, 26.94 , 30.04 , 29.215, 31.49 , 33.305, 27.955, 27.505,
       24.532, 25.59 , 23.665, 20.677, 22.229, 13.36 , 13.68 , 14.58 ,
       14.11 , 15.771, 11.74 , 12.88 , 12.41 , 12.93 , 20.814, 14.84 ,
       13.655, 13.505, 14.12 , 18.945, 22.608, 20.985, 26.355, 22.475,
       26.38 , 23.075, 27.345, 26.52 , 13.165, 14.461, 13.51 , 14.08 ,
       14.7  , 12.09 , 13.17 , 13.285, 14.05 , 12.57 , 12.22 , 13.39 ,
       18.315, 16.355, 18.232, 18.143, 21.964, 26.791, 11.6  , 12.25 ,
       12.85 , 12.405, 18.36 , 22.01 , 21.475, 23.06 , 21.395, 20.363,
       21.211, 25.97 , 14.51 , 15.1  , 29.29 , 24.955, 21.406, 19.799,
       15.052, 23.161, 19.704, 12.335, 20.328, 19.2  , 16.091, 30.8  ,
       25.355, 30.985, 24.683, 16.17 , 16.005, 17.733, 15.416, 13.27 ,
       13.985, 13.682, 14.162, 27.589, 27.52 , 26.374, 31.565, 31.655,
       27.2  , 25.14 , 25.894, 23.937, 25.483, 30.27 , 19.265, 17.844,
       15.739, 15.963, 15.095, 14.73 , 15.155, 14.28 , 17.063, 16.145,
       15.59 , 17.741, 20.125, 19.723, 15.197, 27.735, 23.513, 19.8  ,
       23.011, 23.939, 25.579, 23.83 , 18.883, 29.09 , 19.034, 23.372,
       22.552, 21.651, 23.74 , 32.475, 26.716, 25.184, 24.621, 25.985,
       27.37 , 16.47 , 15.455, 16.324, 14.885, 21.498, 20.92 , 22.868,
       21.17 , 29.822, 25.545, 29.26 , 32.76 , 19.692, 18.376, 18.511,
       18.243, 29.491, 31.605, 27.63 , 25.605, 20.127, 13.325, 20.083,
       19.777, 17.224, 15.645, 13.795, 13.721, 13.255, 31.509, 29.664,
       34.422, 25.347, 32.83 , 16.783, 17.207, 15.684, 15.347, 18.047,
       20.268, 19.212, 18.31 , 15.715, 15.54 , 15.728, 15.827, 29.845,
       24.505, 26.639, 24.875, 31.113, 32.455, 30.524, 29.805, 21.83 ,
       22.241, 22.091, 40.864, 35.405, 34.493, 36.879, 35.543, 19.774,
       18.822, 19.41 , 19.021, 20.24 , 20.714, 25.06 , 20.217, 19.766,
       20.605, 20.692, 18.728, 18.801, 18.922, 17.93 , 18.527, 17.089,
       30.669, 25.813, 26.769, 29.713, 22.99 , 22.98 , 23.342, 24.086,
       21.305, 17.641, 21.712, 16.901, 31.718, 30.461, 21.234, 21.544,
       24.327, 20.296, 20.598, 17.268, 17.873, 17.441, 17.792, 16.473,
       16.152, 19.337, 17.681, 33.499, 33.825, 35.019, 28.428, 25.274,
       21.11 , 27.85 , 22.721, 35.078, 34.343, 33.94 , 36.394, 28.068,
       27.707, 25.415, 32.016, 39.298, 36.591, 33.138, 36.605, 27.891,
       26.249, 25.523, 20.097, 34.689, 29.357, 31.169, 34.957, 32.672,
       43.216, 26.915, 41.027, 43.524, 40.832, 33.598, 30.554, 41.291,
       34.635, 31.819, 27.531, 28.632, 33.461, 32.558, 28.516, 27.104,
       26.251, 24.27 , 31.423, 37.688, 37.707, 35.722, 33.314, 36.708,
       36.518, 34.162, 34.813, 34.688, 32.776, 33.762, 34.166, 32.601,
       30.96 , 30.866, 27.869, 28.67 , 25.289, 25.29 , 21.717, 24.344,
       21.3  , 20.017, 28.51 , 27.919, 33.036, 30.454, 29.085, 27.061,
       24.705, 35.618, 36.07 , 33.005, 37.366, 35.105, 35.821, 35.42 ,
       33.801, 35.872, 33.301, 36.294, 25.658, 30.737, 27.243, 24.066,
       29.933, 34.114, 26.508, 26.806, 41.953, 32.689, 28.782, 30.12 ])