In [13]:
import pandas as pd
import numpy as np
from sklearn import pipeline,preprocessing,metrics,model_selection,ensemble
from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import OneHotEncoder
import statsmodels.api as sm

In [14]:
data=pd.read_excel(r'G:\DBA\MOD_2_core analytics\django\djangoTut\mpgWebApp\models\mileage_new.xls')

In [15]:
data

,mpg,cyl,disp,hp,wt,acc,modyr,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [16]:
mapper = DataFrameMapper([
                        (['cyl','disp','wt','acc','modyr'],preprocessing.StandardScaler()),
                        (['origin'],preprocessing.OneHotEncoder(handle_unknown = 'ignore'))
                        ])

In [17]:
# target and features
y=data['mpg']
X=data.iloc[:,:-2] 

# Fit a regression model
res = sm.OLS(y, X).fit()
print(res.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                    mpg   R-squared (uncentered):                   1.000
Model:                            OLS   Adj. R-squared (uncentered):              1.000
Method:                 Least Squares   F-statistic:                          8.070e+30
Date:                Sat, 04 Sep 2021   Prob (F-statistic):                        0.00
Time:                        08:34:31   Log-Likelihood:                          11350.
No. Observations:                 392   AIC:                                 -2.269e+04
Df Residuals:                     385   BIC:                                 -2.266e+04
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
mpg            1.0000   9.54e-16   1.05e+15      0.000       1.000       1.000
cyl         1.166e-15    6.2e-15      0.188      0.851    -1.1e-14    1.34e-14
disp        1.769e-16   1.39e-16      1.274      0.203   -9.61e-17     4.5e-16
hp         -6.592e-17    2.3e-16     -0.286      0.775   -5.18e-16    3.86e-16
wt         -3.621e-17   1.39e-17     -2.612      0.009   -6.35e-17   -8.95e-18
acc         4.441e-16   1.74e-15      0.256      0.798   -2.97e-15    3.86e-15
modyr      -1.943e-16   7.37e-16     -0.264      0.792   -1.64e-15    1.25e-15
==============================================================================
Omnibus:                       12.030   Durbin-Watson:                   0.076
Prob(Omnibus):                  0.002   Jarque-Bera (JB):                9.239
Skew:                           0.276   Prob(JB):                      0.00986
Kurtosis:                       2.489   Cond. No.                     5.86e+03
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 5.86e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [18]:
X=data.iloc[:,:-2] 
X

      mpg  cyl   disp   hp    wt   acc  modyr
0    18.0    8  307.0  130  3504  12.0     70
1    15.0    8  350.0  165  3693  11.5     70
2    18.0    8  318.0  150  3436  11.0     70
3    16.0    8  304.0  150  3433  12.0     70
4    17.0    8  302.0  140  3449  10.5     70
..    ...  ...    ...  ...   ...   ...    ...
387  27.0    4  140.0   86  2790  15.6     82
388  44.0    4   97.0   52  2130  24.6     82
389  32.0    4  135.0   84  2295  11.6     82
390  28.0    4  120.0   79  2625  18.6     82
391  31.0    4  119.0   82  2720  19.4     82

[392 rows x 7 columns]

In [20]:
from sklearn.linear_model import LinearRegression
pipeline_obj=pipeline.Pipeline([
    ('mapper',mapper),
    ("model",sklearn.linear_model.LinearRegression())
])

AttributeError: module 'sklearn.ensemble' has no attribute 'LinearRegression'